[project]
name = "flaskr"
version = "1.0.0"
description = "Flask Blog"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage.run]
brance = true
source = ["flaskr"]